# docker-compose file for SQLite
owncloud:
  image: l3iggs/owncloud
  restart: always
  # ports:
  #   - "8000:80"
  # links:
  #   - mysql
  environment:
    VIRTUAL_HOST: myhost.mydomain,www.myhost.mydomain
    START_MYSQL: false
    TARGET_SUBDIR: /
  volumes:
    # requires proper authorizations, see rights.sh
    # https://github.com/l3iggs/docker-owncloud/wiki/Store-your-data-outside-of-the-container
    - ./owncloud/volumes/data:/usr/share/webapps/owncloud/data
    - ./owncloud/volumes/config:/etc/webapps/owncloud/config
